// ***** REFOCTER needed **** 

//// Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be:
// OUTPUT : 1, 2, 3,5,8,13,21,34,55,89,....
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
let sum = 0;
function fibonacci(num) {
  
    if (num <= 2 ){
      // console.log(num)
      return num
    } else {
      // console.log(fibonacci(num - 2) + fibonacci(num + 1))
      return fibonacci(num - 1) + fibonacci(num - 2)
    } 
  }
  

// fibonacci(10)
for(let i = 1; i < 4000000000; i++) {
    // console.log(fibonacci(i));
    if( fibonacci(i) % 2 == 0 ) {
      sum += fibonacci(i)
    }
  
}
console.log(sum)
// for (var num = 0; num < 10; num++) {  
//   console.log(fibonacci(num))
// }



// for (var i = 0; i < 10; i++) {
//   num = num
// }